# Build image in Cloud Build, push it to Container Registry, and deploy on Cloud Run

steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -t gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA -f cloud_run/Dockerfile .

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    waitFor:
      - "build image"
    args:
      - "push"
      - "gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"

  - id: "layer for sql-proxy"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    waitFor:
      - "push image"
    args:
      - "-c"
      - |
        echo "FROM gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
        COPY --from=gcr.io/cloud-sql-connectors/cloud-sql-proxy /cloud-sql-proxy /cloudsql/cloud-sql-proxy" > Dockerfile-proxy;
        docker build -f Dockerfile-proxy -t gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA-proxy .

  - id: "deploy on cloudrun"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    waitFor:
      - "collect static"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image gcr.io/$_PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA \
          --region $_DEPLOY_REGION \
          --platform $_PLATFORM
